### ISSUE TITLE
error on load refFunction in qgis master

### ISSUE THREAD

**Issue by antoniusz** [enricofer/refFunctions#1]
Hi,

I'm getting this error on qgis master startup
Maybe, could be related to this:
https://github.com/qgis/QGIS/commit/6a17a60ae23a0b7010682d91aa7fa2de795bd748

Nem tudom betölteni a refFunctions modult due to an error when calling its classFactory() method

Traceback (most recent call last):
  File "/home/toni/FLOSS/qgis/apps_master/share/qgis/python/qgis/utils.py", line 220, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/toni/.qgis2/python/plugins/refFunctions/**init**.py", line 26, in classFactory
    from reffunctions import refFunctions
  File "/home/toni/FLOSS/qgis/apps_master/share/qgis/python/qgis/utils.py", line 479, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/toni/.qgis2/python/plugins/refFunctions/reffunctions.py", line 92, in 
    @qgsfunction(3, "Reference", register=False, usesgeometry=True)
  File "/home/toni/FLOSS/qgis/apps_master/share/qgis/python/qgis/core/__init__.py", line 88, in wrapper
    return register_function(func, args, group, usesgeometry, **kwargs)
TypeError: register_function() got multiple values for keyword argument 'usesgeometry'

Python verzió: 2.7.8 (default, Oct 18 2014, 12:52:27) [GCC 4.9.1]
QGIS verzió: 2.7.0-Master Master, 1a46c40

**Comment by enricofer** [comment]
I notice the same behaviour. But I have no solutions.
There are new contibution to source code that changes the method of registering new expression function. Please submit a post to Qgis dev mailing list on nabble.

**Comment by enricofer** [comment]
The issue has been fixed: http://hub.qgis.org/issues/11961
Thank you for submission

**Comment by enricofer** [comment]
Migration to core: https://github.com/enricofer/refFunctions/wiki/Migration-to-core
