### ISSUE TITLE
Uncaught ImportError: cannot import name uic


### ISSUE THREAD

**Issue by dthgeek** [enricofer/refFunctions#12]
Couldn't load plugin refFunctions due to an error when calling its classFactory() method
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/daniel/.qgis2/python/plugins/refFunctions/__init__.py", line 26, in classFactory
    from .reffunctions import refFunctions
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/daniel/.qgis2/python/plugins/refFunctions/reffunctions.py", line 37, in <module>
    from .reffunctionsdialog import refFunctionsDialog
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/daniel/.qgis2/python/plugins/refFunctions/reffunctionsdialog.py", line 24, in <module>
    from qgis.PyQt import QtGui, uic
ImportError: cannot import name uic

```
refFunctions 1.4, QGIS 2.18.11 on Linux 3.13.0-126-lowlatency

**Comment by enricofer** [comment]
Migration to core: https://github.com/enricofer/refFunctions/wiki/Migration-to-core
